config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  
  # https://stackoverflow.com/a/13219048
  # authenticated :user do
  #   root 'users#home', as: :authenticated_root
  # end
  root 'static_pages#index'

  get ':account_id/home', to: 'accounts#home', as: 'account_home', constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/', to: redirect('%{account_id}/home'), constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/my/profile', to: 'users#show', as: 'users_profile', constraints: { account_id: /[0-9]{8}/ }
  scope ':account_id', constraints: { account_id: /[0-9]{8}/ } do 
    resources :folders
    resources :notes
  end
  
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :account
  belongs_to :folder, optional: true
  belongs_to :user
  validates :title, presence: true, unless: :body?
  validates :body, presence: true, unless: :title?
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account
  before_action :set_note, only: [:show, :edit, :update, :destroy]


  def index
    # @notes = Note.all
    authorize Note
    @folders = @params_account.folders.roots
    @folder = @params_account.folders.new
    @note = @params_account.notes.new
    @notes = @params_account.notes.where(folder_id: nil)
    # @notes = @params_account.notes.where(account_id: @params_account.id, folder_id: @params_folder.id)
    # authorize(@params_account, policy: NotePolicy)
  end


  def show
    authorize @note
  end


  def new
    @note = @params_account.notes.new
    authorize @note
  end


  def edit
    authorize @note
  end


  def create
    @note = @params_account.notes.build(note_params.merge(user_id: current_user.id))

    authorize @note

    if @note.save
      redirect_to helpers.redirect_to_notes_folder_if_present_else_note_index, flash: { success: "Note was successfully created." }
    else
      # need to ajax this form so you don't leave the folder#show and don't have this render on a different URL
      # @params_folder = @note.folder
      # @notes = @params_account.notes.all
      # flash.now[:error] = "Note not saved. See error(s) below."
      # render 'folders/show'
      respond_to do |format|
        format.js
      end
    end
  end


  def update
    authorize @note
    if @note.update(note_params.merge(user_id: current_user.id))
      redirect_to helpers.redirect_to_notes_folder_if_present_else_note_index, notice: 'Note was successfully updated.'
    else
      respond_to do |format|
        format.js
      end
    end
  end


  def destroy
    authorize @note
    @note.destroy
    redirect_to helpers.redirect_to_notes_folder_if_present_else_note_index, notice: 'Note was successfully destroyed.'
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_note
      @note = @params_account.notes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:folder_id, :title, :body)
    end

end

app/helpers/notes_helper.rb
module NotesHelper

  def redirect_to_notes_folder_if_present_else_note_index
    if @note.folder_id.present?
      if action_name == 'destroy'
        folder_path(@params_account.hash_id, @note.folder.slug)
      else
        folder_path(@params_account.hash_id, @note.folder.slug, anchor: @note.id)
      end
    else
      if action_name == 'destroy'
        notes_path(@params_account.hash_id)
      else
        notes_path(@params_account.hash_id, anchor: @note.id)
      end
    end
  end
  
end

app/views/notes/_form.html.erb
<div class="main__new_note_form-container">

  <%= form_for(@note, :url => @note.persisted? ? note_path(account_id: @params_account.hash_id, id: @note) : notes_path(account_id: @params_account.hash_id, id: @note), remote: true) do |form| %>
    <div id="note_form_errors">
      <%= render 'notes/form_errors' %>
    </div>

    <%= form.hidden_field :folder_id, value: @params_folder.id if @params_folder %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.hidden_field :body, id: :note_body %>
      <trix-editor input="note_body"></trix-editor>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/notes/_form_errors.html.erb
<% if @note.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

    <ul>
    <% @note.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/notes/create.js.erb
$("#note_form_errors").html("<%= escape_javascript(render 'form_errors') %>");

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', note_path(@params_account.hash_id, @note) %> |
<%= link_to 'Back', redirect_to_notes_folder_if_present_else_note_index %>

app/views/notes/index.html.erb
<%= render 'shared/breadcrumbs' %>

<%= render 'shared/subfolders_listing' %>

<hr>

<%= render 'notes/form', note: @note %>


<%= render 'shared/notes_listing' %>


<%#= link_to 'New Note', new_note_path(account_id: @params_account.hash_id) %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= sanitize @note.body %>
</p>

<%= link_to 'Edit', edit_note_path(@params_account.hash_id, @note) %> |
<%= link_to 'Back', redirect_to_notes_folder_if_present_else_note_index %> |
<%= link_to 'Destroy', note_path(@params_account.hash_id, @note), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/notes/update.js.erb
$("#note_form_errors").html("<%= escape_javascript(render 'form_errors') %>");