config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  
  # https://stackoverflow.com/a/13219048
  # authenticated :user do
  #   root 'users#home', as: :authenticated_root
  # end
  root 'static_pages#index'

  get ':account_id/home', to: 'accounts#home', as: 'account_home', constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/', to: redirect('%{account_id}/home'), constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/my/profile', to: 'users#show', as: 'users_profile', constraints: { account_id: /[0-9]{8}/ }
  scope ':account_id', constraints: { account_id: /[0-9]{8}/ } do 
    resources :folders
    resources :notes
  end
  
end

app/models/folder.rb
class Folder < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [ :sequentially_slugged, :scoped ], scope: :account_id
  
  has_ancestry

  belongs_to :account
  has_many :notes, dependent: :destroy

  validates :name, presence: true

  def should_generate_new_friendly_id?
    name_changed?
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account
  before_action :set_folder, only: [ :show, :edit, :update ]

  def index
    authorize Folder
    @folders = @params_account.folders.all
    @folder = @params_account.folders.new
    # @params_folder = Folder.friendly.find_by!(account: @params_account.id, name: 'root')
  end

  def show
    authorize @params_folder
    @folder = @params_account.folders.new
    @note = @params_account.notes.new
    @notes = @params_account.notes.where(folder_id: @params_folder.id)
  end

  def new
    @folder = @params_account.folders.new
    authorize @folder
  end


  def edit
    @folder = @params_folder
    authorize @folder
  end


  def create
    @folder = @params_account.folders.build(folder_params)

    authorize @folder

    if @folder.save
      # redirect_to redirect_to_parent_folder_if_present_else_notes_index
      redirect_to folder_path(@params_account.hash_id, @folder.slug), flash: { success: "Folder was successfully created." }
    else
      # @folders = @params_account.folders.all
      # flash.now[:error] = "Folder not saved. See error(s) below."
      # render :index
      respond_to do |format|
        format.js
      end
    end
  end


  def update
    @folder = @params_folder
    authorize @folder
    if @folder.update!(folder_params)
      redirect_to folder_path(@params_account.hash_id, @folder.slug, anchor: @folder.slug), notice: 'Folder was successfully updated.'
    else
      respond_to do |format|
        format.js
      end
    end
  end


  def destroy
    authorize @folder
    @folder.destroy
    redirect_to folder_path(@params_account.hash_id, @folder.parent_id), notice: 'Folder was successfully destroyed.'
  end



  private

    def set_folder
      folder_id = params[:id]
      # verify account_id is an x-digit integer or else 404
      @params_folder = Folder.friendly.find_by!(account: @params_account.id, slug: folder_id)
    end

    def folder_params
      params.require(:folder).permit(:name, :parent_id)
    end

    def redirect_to_parent_folder_if_present_else_notes_index
      if @folder.parent.present?
        redirect_url = folder_path(@params_account.hash_id, @folder.parent.slug, anchor: @folder.slug)
      else
        redirect_url = notes_path(@params_account.hash_id, anchor: @folder.slug)
      end
    end

end

app/helpers/folders_helper.rb
module FoldersHelper

  def nested_folders(folders)
    folders.map do |folder, sub_folders|
      render(folder) + content_tag(:div, nested_folders(sub_folders), :class => "nested_folders")
    end.join.html_safe
  end

end

app/views/folders/_folder.html.erb
<%= link_to folder.name, folder_path(@params_account.hash_id, folder.slug) %> [<%= link_to 'Edit', edit_folder_path(@params_account.hash_id, folder.slug) %>]<br>

app/views/folders/_form.html.erb
<%= form_for(@folder, url: @folder.persisted? ? folder_path(account_id: @params_account.hash_id, id: @folder) : folders_path(account_id: @params_account.hash_id, id: @folder), remote: true) do |form| %>
  <div id="folder_form_errors">
    <%= render 'folders/form_errors' %>
  </div>

  <% unless @folder.persisted? %>

    <%= form.hidden_field :parent_id, value: @params_folder.id if @params_folder %>

  <% end %>

  <%= form.text_field :name, placeholder: "New Subfolder Name", data: { target: "visibility.focus"} %> <%= form.submit %>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close"  data-action="visibility#hide">
    <span aria-hidden="true">&times;</span>
  </button>
  
<% end %>

app/views/folders/_form_errors.html.erb
<% if @folder.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

    <ul>
    <% @folder.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/folders/create.js.erb
$("#folder_form_errors").html("<%= escape_javascript(render 'form_errors') %>");

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @params_folder %>

<%= link_to 'Show', folder_path(@params_account.hash_id, @params_folder) %> |
<%= link_to 'Back', folder_path(@params_account.hash_id) %>

app/views/folders/index.html.erb
<h1>Folders</h1>


<%= nested_folders @folders.arrange(order: :name) %>

<%= render "form" %>

app/views/folders/show.html.erb
<%= render 'shared/breadcrumbs' %>

<%= render 'shared/subfolders_listing' %>

<%= render 'notes/form', note: @note %>

<%= render 'shared/notes_listing' %>

app/views/folders/update.js.erb
$("#folder_form_errors").html("<%= escape_javascript(render 'form_errors') %>");