config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  
  # https://stackoverflow.com/a/13219048
  # authenticated :user do
  #   root 'users#home', as: :authenticated_root
  # end
  root 'static_pages#index'

  get ':account_id/home', to: 'accounts#home', as: 'account_home', constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/', to: redirect('%{account_id}/home'), constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/my/profile', to: 'users#show', as: 'users_profile', constraints: { account_id: /[0-9]{8}/ }
  scope ':account_id', constraints: { account_id: /[0-9]{8}/ } do 
    resources :folders
    resources :notes
  end
  
end

app/views/shared/_breadcrumbs.erb
<div class="main__breadcrumb-container">
  <% if @params_folder %>

    <%= link_to "", notes_path(@params_account.hash_id), class: "main__breadcrumb__home-button btn btn--icon btn--home-icon" %>

  <% else %>

    <div class="main__breadcrumb__home-button btn--icon btn--home-dark-icon"></div>

  <% end %>

  <% if @params_folder %>

    <% @params_folder.ancestors.each do |a| %>

      <%= image_tag image_path "icons/breadcrumb-arrow-right.svg" %> <%= link_to a.name, folder_path(a.account.hash_id, a.slug) %>

    <% end %>

    <%= image_tag image_path("icons/breadcrumb-arrow-right.svg"), class: "main__breadcrumb__arrow" %> <span class="present-folder"><%= @params_folder.name %></span>

  <% end %>

</div>

<%= render 'shared/current_folder_action_bar' %>

app/views/shared/_current_folder_action_bar.erb
<div class="current-folder-action-bar" style="text-align: center;">
  current folder actions / settings
</div>

app/views/shared/_notes_listing.erb
<% if @notes %>

  <section class="main__notes_listing-container">
    <header>
      <h3 class="main__notes_listing__header header__bgline"><span>Notes</span></h3>
      <aside class="main__notes_listing__header__toolbar">
        <button class="main__notes_listing__header__toolbar__folder-add-button btn btn--icon btn--folder-add-icon" data-controller="subfolder-add"></button>
      </aside>
    </header>

    <%= render 'shared/notes_listing/titles_list' %>

    <%= render 'shared/notes_listing/notes_list' %>



  </section>

<% else %>
  No notes in this folder.
<% end %>












<%# reference code (notes action links/paths) %>

<% if false %>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>    
        <% @notes.each do |note| %>
          <tr>
            <td><%= note.title %></td>
            <td><%= sanitize note.body %></td>
            <td><%= link_to 'Show', note_path(@params_account.hash_id, note) %></td>
            <td><%= link_to 'Edit', edit_note_path(@params_account.hash_id, note) %></td>
            <td><%= link_to 'Destroy', note_path(@params_account.hash_id, note), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    </tbody>
  </table>

<% end %>

app/views/shared/_subfolders_listing.erb
<section class="main__subfolders-container" data-controller="visibility">
  <header>
    <h3 class="main__subfolders__header header__bgline"><span>Subfolders</span></h3>
    <aside class="main__subfolders__header__toolbar">
      <button class="main__subfolder__header__toolbar__folder-add-button btn btn--icon btn--folder-add-icon" data-action="visibility#show"></button>
    </aside>
  </header>

  <div class="main__subfolder__link-box new-folder-form hidden" data-target="visibility.element">
    
    <%= render "folders/form" %>

  </div>

  <% if @params_folder %>

    <% @subfolder_list = @params_folder.children.arrange(order: :name) %>

  <% elsif @folders %>

    <% @subfolder_list = @folders.arrange(order: :name) %>

  <% end %>

  <% unless @subfolder_list.empty? %>

    <% @subfolder_list.each do |a| %>

      <%= link_to a.first.name, folder_path(a.first.account.hash_id, a.first.slug), class: "main__subfolder__link-box" %>

    <% end %>

  <% else %>

    <div class="empty_list">

      No subfolders here yet.

    </div>

  <% end %>

</section>