config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }
  
  # https://stackoverflow.com/a/13219048
  # authenticated :user do
  #   root 'users#home', as: :authenticated_root
  # end
  root 'static_pages#index'

  get ':account_id/home', to: 'accounts#home', as: 'account_home', constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/', to: redirect('%{account_id}/home'), constraints: { account_id: /[0-9]{8}/ }
  get ':account_id/my/profile', to: 'users#show', as: 'users_profile', constraints: { account_id: /[0-9]{8}/ }
  scope ':account_id', constraints: { account_id: /[0-9]{8}/ } do 
    resources :folders
    resources :notes
  end
  
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% type_class = bootstrap_class_for(message_type) %>
  <%= content_tag(:div, class: ["alert", "#{type_class}", "alert-dismissible", "fade", "show"]) do %>
    <%= content_tag(:div, class: ["container"]) do %>
      <%= content_tag(:div, class: ["row"]) do %>
        <%= content_tag(:div, class: ["col-11", "col-no-padding"]) do %>
          <%= message %>
        <% end %>
        <%= content_tag(:div, class: ["col-1", "col-no-padding"]) do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer__wrap">

  <div class="container">

    <div class="row">

      footer

    </div>

  </div>

</div>

app/views/layouts/_header.html.erb
<div class="header__wrap">

  <div class="container">

    <div class="row">

      <div class="col header__content-left-wrap">

        <div class="header__content-left__logo-wrap">

          <%= link_to "", account_home_path(current_user.account.hash_id), class: "header__content-left__logo" %>

        </div>

      </div>

      <div class="col header__content-center-wrap">

        <% if user_signed_in? %>   

          <%= link_to "Folders", folders_path(current_user.account.hash_id) %> |

          <%= link_to "Notes", notes_path(current_user.account.hash_id) %>

        <% else %>

          center area

        <% end %>

      </div>

      <div class="col header__content-right-wrap">

          <% if user_signed_in? %>          

            <div class="header__content-right__account-dropdown-wrap dropdown">

              <button class="header__content-right__account-dropdown-button dropdown-toggle" type="button" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Account</span>
                <%# <i class="fa fa-user-circle-o" aria-hidden="true"></i> %>
                <%= current_user.email %>
              </button>

              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to "Profile", users_profile_path(current_user.account.hash_id), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>

            </div>

          <% else %>

            <%= link_to "Sign Up", new_user_registration_path %> &nbsp;|&nbsp; <%= link_to "Log in", new_user_session_path %>

          <% end %>

      </div>

    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/shared/ie_shim' %>

    <%= render 'layouts/header' %>

    <%= render 'layouts/flash_messages' %>

    <div class="container">

      <div class="row main__wrap">

        <div class="col col-no-padding">

          <%= yield %>

        </div>

      </div>

    </div>

    <%= render 'layouts/footer' %>
    
    <%= render 'layouts/shared/analytics_snip' %>

  </body>
</html>